export const FETCH_PRODUCTS_BY_CATEGORY_REQUEST = "FETCH_PRODUCTS_BY_CATEGORY_REQUEST";
export const FETCH_PRODUCTS_BY_CATEGORY_SUCCESS = "FETCH_PRODUCTS_BY_CATEGORY_SUCCESS";
export const FETCH_PRODUCTS_BY_CATEGORY_FAILURE = "FETCH_PRODUCTS_BY_CATEGORY_FAILURE";

export const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS'
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE'