export const SET_CATEGORY_FILTER = "SET_CATEGORY_FILTER";
export const SET_SIZE_FILTER = "SET_SIZE_FILTER";
export const SET_PRICE_RANGE_FILTER = "SET_PRICE_RANGE_FILTER";
export const SET_DISCOUNT_FILTER = "SET_DISCOUNT_FILTER";
export const SET_STOCK_FILTER = "SET_STOCK_FILTER";
export const CLEAR_ALL_FILTERS = "CLEAR_ALL_FILTERS";